# Generated by Django 3.2 on 2025-05-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
